name: Docker

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        registry-url: https://ghcr.io/RaiRuhi/rsem1.2.25/
        env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
